site_name: libctl Documentation
site_author: S. G. Johnson et al.
repo_url: https://github.com/stevengj/libctl/

docs_dir: 'doc/docs'
site_dir: 'doc/site'

theme_dir: 'doc/libctl-mkdocs-theme'
theme: readthedocs

python:
   version: 2 # for unicode
   setup_py_install: True

markdown_extensions:
    - wikilinks
    - toc:
        title: Table of Contents
    - attr_list
    - fenced_code
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript:
 - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML'
 - 'js/mathjaxhelper.js'
 - 'js/extra.js'

pages:
- Libctl Overview: index.md
- Libctl Manual:
    - Introduction: Libctl_Introduction.md
    - Basic user experience: Libctl_Basic_User_Experience.md
    - Advanced user experience: Libctl_Advanced_User_Experience.md
    - Developer experience: Libctl_Developer_Experience.md
    - User reference: Libctl_User_Reference.md
    - Guile and scheme links: Guile_and_Scheme_links.md
- License and copyright: Libctl_License_and_Copyright.md
- Release notes: Libctl_release_notes.md
